create table if not exists public.appointment_bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  reference text not null,
  name text not null,
  email text not null,
  phone text not null,
  company text,
  service text not null default 'Website development',
  preferred_date date,
  preferred_day_label text,
  preferred_time text not null,
  goal text not null,
  source text not null default 'corevix_booking_form',
  status text not null default 'new',
  user_agent text
);

alter table public.appointment_bookings enable row level security;

create index if not exists appointment_bookings_created_at_idx
  on public.appointment_bookings (created_at desc);

create index if not exists appointment_bookings_status_idx
  on public.appointment_bookings (status);

create index if not exists appointment_bookings_preferred_date_idx
  on public.appointment_bookings (preferred_date);

create unique index if not exists appointment_bookings_reference_idx
  on public.appointment_bookings (reference);

comment on table public.appointment_bookings is
  'Appointment requests submitted from the Corevix Solutions booking form.';

comment on column public.appointment_bookings.status is
  'Appointment handling state, for example new, contacted, confirmed, completed, cancelled.';
