create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  company text,
  service text not null default 'General enquiry',
  message text not null,
  source text not null default 'corevix_contact_form',
  status text not null default 'new',
  user_agent text
);

alter table public.contact_messages enable row level security;

create index if not exists contact_messages_created_at_idx
  on public.contact_messages (created_at desc);

create index if not exists contact_messages_status_idx
  on public.contact_messages (status);

comment on table public.contact_messages is
  'Website contact form submissions from Corevix Solutions.';

comment on column public.contact_messages.status is
  'Lead handling state, for example new, contacted, qualified, closed.';
