create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id text,
  session_id text,
  path text not null default '/',
  referrer text,
  language text,
  timezone text,
  screen_width integer,
  screen_height integer,
  source text not null default 'website',
  user_agent text
);

create index if not exists visitor_events_created_at_idx
  on public.visitor_events (created_at desc);

create index if not exists visitor_events_visitor_id_idx
  on public.visitor_events (visitor_id);

create index if not exists visitor_events_path_idx
  on public.visitor_events (path);

alter table public.visitor_events enable row level security;

comment on table public.visitor_events is
  'Private visitor event log for the Corevix Solutions admin dashboard. Insert and read through server-side service role only.';
